services:
  vproapp:
    build: 
      context: ./app
    image: kubesahar/vproapp
    container_name: vproapp
    ports: 
    - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vprodb:
    build: 
       context: ./db
    image: kubesahar/vprodb
    container_name: vprodb
    ports:
    - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass
    volumes:
    - dbdatavolume:/var/lib/mysql

  vprocache01:
    image: memcached
    container_name: vprocache01
    ports:
    - "11211:11211"

  vpromq01:
    image: rabbitmq
    container_name: vpromq01
    ports:
    - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  web:
    build: 
      context: ./web
    image: kubesahar/vproweb
    container_name: vproweb
    ports:
      - "80:80"

volumes:
  dbdatavolume: {}
  vproappdata: {}